language: node_js
node_js: 
    - "12"
before_script:
    - npm i
script:    
    - npm run build    
deploy: 
    provider: npm
    skip_cleanup: true
    email: $API_ACCOUNT
    api_key: $API_KEY
    on:
        branch: master